config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "buyers#index"

  resources :sellers  
  resources :buyers
  resources :carts
  resources :lineitems
  resources :home

  get "/payment" ,to: "lineitems#payment" 
  get "/mydash" ,to: "sellers#mydash" 
  patch "/payment_type" ,to: "lineitems#payment_type"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/lineitem.rb
class Lineitem < ApplicationRecord
    belongs_to :user
    belongs_to :order
    belongs_to :product
end
    

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    has_many :lineitems
    enum :status, [:cart,:payment,:delivery,:shipped,:canceled], _default: :cart
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :user
    has_many :lineitems

    def sum
       @order = current_user.products
       @products= @lineitem.price*@lineitem.quantity
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :products
  has_many :orders
  has_many :lineitems
  devise :database_authenticatable, :registerable,:recoverable, :rememberable, :validatable
 
  def seller?
    role == "seller"
  end

  def buyer?
    role == "buyer"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(a)
    if a.seller?
      sellers_path
    elsif a.buyer?
      buyers_path
    else
      redirect_to root_path
    end 
  end
 
  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :city, :state, :address, :postal_code, :role, :email, :password)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :city, :state, :address, :postal_code, :role, :email, :password, :current_password)}
  end
end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
    def index
        @products=Product.all
    end
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    
end

app/controllers/lineitems_controller.rb
class LineitemsController < ApplicationController
  before_action :authenticate_user!
    def index
      @order=current_user.orders.last
        if @order
          if @order.cart?
            @lineitems = @order.lineitems
          else
            @lineitem=nil
          end
        else
         @lineitem=nil
        end 
    end

    def create
      @user=User.find(current_user.id)
      @order=@user.orders.last
        if @order 
          if @order.cart?
            @lineitem = @user.orders.last.lineitems.new(carts_params)
            @lineitem.user_id = current_user.id
              if @user.orders.last.lineitems.where(product_id: @lineitem.product_id).empty?
                if @lineitem.save
                  @order = @user.orders.last
                  @order.total_price = @order.total_price + (@lineitem.price*@lineitem.quantity)
                  @order.total_quantity = @order.total_quantity + @lineitem.quantity
                  @order.save
                  redirect_to buyers_path
                end
                else    
                  @lineitems = @user.orders.last.lineitems.where(product_id:  @lineitem.product_id).first
                  @lineitems.quantity =  @lineitems.quantity + @lineitem.quantity 
                  @lineitems.save
                  @order = @user.orders.last
                    if  @user.orders.last.lineitems.count > 1
                        @order.total_price = @order.total_price + (@lineitems.price*@lineitems.quantity)
                        @order.total_quantity =  @order.total_quantity + @lineitems.quantity
                        @order.save
                    else     
                        @order.total_price = @lineitems.price*@lineitems.quantity
                        @order.total_quantity = @lineitems.quantity
                        @order.save
                    end
                    redirect_to buyers_path
                end 
            else 
             sample
            end
        else
         sample
        end    
  end
    def destroy
     @lineitem = Lineitem.find(params[:id])
     @lineitem.destroy
     redirect_to lineitems_path
    end
      
    def payment
     @user=User.find(current_user.id)
    end

    def payment_type
      @user=User.find(current_user.id)
      @order=@user.orders.last
      @order.update(payment_para)
      @order.shipped!
      if @order.save
        flash[:message] = "Your Order is placed"
        redirect_to buyers_path
      end
    end
      
      private
      def carts_params
       params.permit(:price,:quantity,:product_id)
      end

      def payment_para
        params.permit(:payment_mode)
      end

      def sample
        @order = @user.orders.new()
          if @order.save
            @order.cart!
            @lineitem = @user.orders.last.lineitems.new(carts_params)
            @lineitem.user_id = current_user.id
              if @lineitem.save
                @order = @user.orders.last
                @order.total_price = @order.total_price + (@lineitem.price*@lineitem.quantity)
                @order.total_quantity = @order.total_quantity + @lineitem.quantity
                @order.save
                redirect_to buyers_path
              end
         end
      end   
end
  

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  def index
    @products=current_user.products   
  end
  
  def new
      @product = Product.new
  end
  
  def create
    @product=current_user.products.new(product_params)
      if @product.save
       redirect_to sellers_path
      else
       render :new, status: :unprocessable_entity
      end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
     if @product.update(product_params)
      redirect_to sellers_path
     else
      render :edit, status: :unprocessable_entity
     end
  end

  def destroy
    @product = current_user.products.first
    @product.destroy
    redirect_to sellers_path
  end

  def mydash
    @a=Lineitem.joins(:product).where("products.user_id =? ", 1)
    @total_price=0
    @total_quantity=0
    @a.each do |product|
    @total_price=@total_price+(product.price*product.quantity)
    @total_quantity=@total_quantity+product.quantity
    end
  end
    
  private
   def product_params
    params.require(:product).permit(:title, :discription,:price)
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lineitems_helper.rb
module LineitemsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/buyers/index.html.erb
<% if user_signed_in? %> 
    <div class="btn-group" role="group">
    <button type="button" class="btn btn-danger"><%=button_to "logout", destroy_user_session_path, method: :delete %></button> 
    </div> 
    
    
<%else%>
    <div class="btn-group" role="group">
    <button type="button" class="btn btn-success"><%=button_to "login", new_user_session_path, method: :get %></button> 
    </div>
    
<%end%>


<table class='table'>
<thead>
    <tr>
        <th>Name</th><th>Price</th><th>quantity</th>
    <tr>
</thead>
<tbody>
    <%@products.each do |product|%>
    <tr>
        <%= form_with model: @product, url:lineitems_path, method: :post do |form| %>
        <%=form.hidden_field :product_id, value: product.id%>
        <td><%=form.label product.title%></td>
        <td><%=form.label product.price%></td>
        <%=form.hidden_field :price, value:product.price%>
        <td><%=form.number_field :quantity, value:0, min:0%></td>
        <td><%=form.submit "Add to cart"%></td>
        <%end%>
    </tr>
    <% end %>
</tbody>
</table>

<div class="btn-group" role="group">
<button type="button" class="btn btn-success"><%=link_to "Go to cart", lineitems_path%></button> 
</div>

app/views/home/index.html.erb
<h1>Welcome to home pages</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body class=bg-grey>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>           
    <%= yield %>
  </body>
</html>

app/views/lineitems/index.html.erb
<table class ='table'>
<tbody> 
<thead>
    <tr>
        <th>Name</th><th>Price</th><th>quantity</th><th>subtotal</th>
    </tr>
</thead>
    <% if @lineitems != nil %>
    
        <%@lineitems.each do |lineitem|%>
            <%@product =Product.find(lineitem.product_id)%>
        <tr>
            <td><%= @product.title%></td>
            <td><%=lineitem.price%></td>
            <td><%=lineitem.quantity%></td>
            <td><%=lineitem.price * lineitem.quantity%></td>
            <td><%=button_to "Remove from cart", lineitem_path(lineitem), method: :delete%></td>
        </tr>
        <% end %>
    <%else%>
       <h1>carts is empty</h1>

    <% end %>
</tbody>
</table>




<div class="btn-group" role="group">
<button type="button" class="btn btn-success"><%=link_to "Order Now",payment_path,method: :get %></button> 
</div>

app/views/lineitems/payment.html.erb
<h1>Payment process</h1>

<%= form_with model: @lineitem , url:payment_type_path, method: :PATCH do |form| %>
  
  <div>
    <%= form.label :payment_mode %><br>
    <%= form.text_field :payment_mode %>  
  </div>
  

  <div class="alert alert-success" role="alert">
  <div class="btn-group" role="group">
  <button type="button" class="btn btn-primary"><%=form.submit%></button> 
  
  </div>
    </div>
  
<% end %>

<%=flash[:message] %>

app/views/sellers/_form.html.erb
<h1>New Product</h1>

<%= form_with model: @product, url:sellers_path, method: :post do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :discription %><br>
    <%= form.text_area :discription %>
  </div>
  <div>
    <%= form.label :price %><br>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sellers/edit.html.erb
<h1>New Product</h1>

<%= form_with model: @product, url:seller_path(@product), method: :patch do |form| %>
<div>
  <%= form.label :title %><br>
  <%= form.text_field :title %>
</div>

<div>
  <%= form.label :discription %><br>
  <%= form.text_area :discription %>
</div>
<div>
  <%= form.label :price %><br>
  <%= form.text_field :price %>
</div>

<div>
  <%= form.submit %>
</div>
<% end %>

app/views/sellers/index.html.erb
<br> <br>
<% if user_signed_in? %>     
  <%=button_to "logout", destroy_user_session_path, method: :delete %>
<%else%>
  <%=button_to "login", new_user_session_path, method: :get %>
<%end%>

<table class='table'>
 <thead>
    <tr><th>title</th><th>Price</th><th>Edit Product</th><th>Destroy Product</th></tr>
 </thead>
<tbody>
  <%@products.each do |product|%>
  <tr>
    <td><strong><%=product.title%> </strong></td>
    <td><strong><%=product.price%> </strong></td>
    <td><%= link_to "Edit Product", edit_seller_path(product) %></td>
    <td><%= link_to "Destroy Product", seller_path(product), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></td>
    </tr>
    <%end%>
</tbody>
</table>

<br> <br>
<% if current_user.orders!=nil%>
 <%= button_to "mydash ", mydash_path, method: :get %>
<%end %>

<br> <br>
<button><%= link_to "New Product", new_seller_path %></button>

app/views/sellers/mydash.html.erb
<h1>Seller details</h1>
<table class=table>

<thead>
<th>total quantity</th><th>total price</th>
 </thead>
 <tbody>
 <tr>
    
    <td><%=@total_quantity%></td>
    <td><%=@total_price%></td>
</tr>
</tbody>
</table>

app/views/sellers/new.html.erb
<h1>New Product</h1>

<%= form_with model: @product, url:sellers_path, method: :post do |form| %>
<div>
  <%= form.label :title %><br>
  <%= form.text_field :title %>
</div>

<div>
  <%= form.label :discription %><br>
  <%= form.text_area :discription %>
</div>
<div>
  <%= form.label :price %><br>
  <%= form.text_field :price %>
</div>

<div>
  <%= form.submit %>
</div>
<% end %>